apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "policy-registry-binding"
spec:
  policyName: "policy-registry"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        environment: registry