apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "policy-labels-binding"
spec:
  policyName: "policy-labels"
  validationActions: [Deny]
  paramRef:
    name: "configmap-labels"
    namespace: "kubilab-labels"  
  matchResources:
    namespaceSelector:
      matchLabels:
        environment: labels