apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: policy-labels
spec:
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
      - apiGroups: ["", "apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods", "deployments"]
  validations:
    - expression: >
        has(object.metadata.labels)
        && 'requiredLabels' in params.data
        && params.data['requiredLabels'].split(',').all(req, req.trim() in object.metadata.labels)
      message: "Deployments without required labels are not allowed."